### PR TITLE
Mostly implemented clock like bearing system.

### PR DESCRIPTION
**Pull request by JonathanILevi**
Me and my friends what to use a different bearing system that is, like a clock, based on twelve rather than 360.
This commit just effects the radar indicators and the Helms' tool-tip.  I am working on making it work everywhere.  Changing what radar system is used is a setting in `gameGlobalInfo` and right now the only way to change what type, is to recompile with a different value.

I hope this new bearing system would be appreciable to others.

### CODE REVIEW

**Comment by daid** [comment]
Interresting, sounds like a simple addition.

Instead of setting this as a game_global_info, you could set it as a client configuration from the options.ini, example:
https://github.com/daid/EmptyEpsilon/blob/master/src/main.cpp#L183

**Comment by JonathanILevi** [comment]
I went with game_global_settings because the entire ship should have the same setting or it is a little weird.  But, if you would prefer I could put it in options.ini.

**Comment by JonathanILevi** [comment]
It would also work as a ship setting (so different ship can be different).  Along with warp/jump.  What if there was an interface for selecting per ship settings when a ship is created?

**Comment by JonathanILevi** [comment]
> I think this would work even better if EmptyEpsilon had a "Relative Display Mode" option whereby the ship always points up on the Helm screen (this is a feature in Artemis SBS). Or even if this isn't implemented, at least have the clock numbers revolve around the compass to keep 12 always in the direction the ship is facing (so the directions are always relative to that direction).

That is a cool idea.  I will see if I can implement that when I get around to it (:

**Comment by JonathanILevi** [comment]
The clock like bearing should be working everywhere except the GM screen (which I do not think is important currently).

I added a file for the bearing logic `screenComponents/logic/heading.x` which has show functions that convert a bearing number into the appropriate string.  I am not sure that this is the best place for this file; do you have an idea for a better place? 

The only thing yet to do is a way of changing the setting.

**Pull request closed without merging**
