### PR TITLE
Add 43 _() scenario_81_pvp.lua

### PR DESCRIPTION
**Pull request by muerteFR**
Please @daid look at line 126. I'm not sure this is the best writing.
Thanks

### CODE REVIEW

**Comment by daid** [comment]
Not sure what would be wrong with line 126? But I'm also no native English speaker?

**Comment by muerteFR** [comment]
> Not sure what would be wrong with line 126? But I'm also no native English speaker?
L226 I wanted to say. I was talking about the introduction of tags _().
string.format(args.request .. _(" (%d rep each)"), price),

**Comment by daid** [comment]
Guess `string.format(args.request .. " " .. _("(%d rep each)"), price),` is slightly better, as the leading space isn't really part of the language.

**Comment by muerteFR** [comment]
> Guess `string.format(args.request .. " " .. _("(%d rep each)"), price),` is slightly better, as the leading space isn't really part of the language.

Thanks, it's done

**Pull request merged**
