### PR TITLE
Disabling mac builds

### PR DESCRIPTION
**Pull request by gcask**
Too unstable atm.

### CODE REVIEW

**Comment by k9lego** [comment]
Maybe in the future we could use this to build “untested” release artifacts for MacOS?

**Comment by gcask** [comment]
The instability stems from GitHub infrastructure, not us: https://github.com/actions/virtual-environments/issues/841

We could use a manual flow to build artifacts (I guess), but that's an entirely different topic :)

**Comment by MindTooth** [comment]
This seems to be related to Big Sur (11.0).  Do you accept a patch for using 10.15 instead?

Ref.: https://github.com/actions/virtual-environments/issues/841#issuecomment-767200198

**Comment by gcask** [comment]
fwiw, I've already re-enabled them on my fork: https://github.com/gcask/EmptyEpsilon/blob/master/.github/workflows/cicd.yml

(along with other additions).

**Pull request merged**
