### PR TITLE
Made power and coolant distribution not instantaneous per #134

### PR DESCRIPTION
**Pull request by Fouindor**
Distribution speed hardcoded as of now

### CODE REVIEW

**Comment by Fouindor** [comment]
Per #136, not 134...

**Comment by daid** [comment]
Looks sane. But wouldn't it make sense to just remove the old commandSetSystemCoolant functions instead of adding new ones?

**Comment by Fouindor** [comment]
They are used in the tutorial. Furthermore, I think it could be handy to keep these options for other purpose (like simulating a system down in a mission).

**Comment by Fouindor** [comment]
Thought a bit, and it indeed makes more sense. Replaced the obsolete commands by new SpaceShip functions, setSystemCoolant and setSystemPower

**Comment by daid** [comment]
Ah, yes, wanted to suggest that :D

**Comment by kwadroke** [comment]
I would like to be able to take systems down/offline in a mission.

**Comment by daid** [comment]
You could just keep forcing the power to 0.

And the tutorial uses some tricks like setting the max impulse speed to 0 to disable systems as well.

**Comment by kwadroke** [comment]
That was my plan until we had a way to take systems down. 
But it would be nice to have an indicator saying it was offline.

**Comment by Fouindor** [comment]
Are the changes ok ?

**Comment by daid** [comment]
Didn't have time to check it earlier, looks good now. See you also fixed some minor other things. which is fine.

**Comment by Fouindor** [comment]
Thanks, sorry if I sounded pushy, I was worried that some issues remained.

**Pull request merged**
