### PR TITLE
Scenario Unwanted Visitors

### PR DESCRIPTION
**Pull request by Xansta**
A number of objects are in orbit in this scenario. It can be a challenge for Helm to dock with stations in motion

### CODE REVIEW

**Comment by daid** [comment]
One small request, can you place the ogg files in a subdirectory? The resources directory is getting quite cluttered.

**Comment by Kilted-Klingon** [comment]
I like having stations in orbit and giving the additional challenge to the crew.  8-)

**Comment by Xansta** [comment]
I assume that the `playSoundFile` function can find the file without a subdirectory path

**Comment by daid** [comment]
You need the path relative to the "resources" directory, so your assumption is incorrect I think.

**Comment by Xansta** [comment]
Adjusted the scenario script to look in the subdirectory

**Pull request merged**
