### PR TITLE
allow to configure a callback when an Artifact is picked up

### PR DESCRIPTION
**Pull request by czenker**
Because it was mentioned in the forums recently and it is also on my wishlist I had a look how it was possible to have a callback function if an `Artifact` is picked up.

This pull request depends on [SeriousProton:#23](https://github.com/daid/SeriousProton/pull/23). But if both are approved I think there are lot more places to utilize this pattern – like when a ship is destroyed, docks or undocks a station etc.

Here is how it could be used:

    function init()
        PlayerSpaceship():
            setTemplate("Piranha"):
            setFaction("Human Navy"):
            setCallSign("Thief")
        Artifact():
            setCallSign("Stack of Gold"):
            setPickUpCallback(function(foo, bar)
                print(foo:getCallSign() .. " picked up " .. bar:getCallSign())
            end)
    end

### CODE REVIEW

**Comment by daid** [comment]
I think you also patched SeriousProton, but didn't submit a patch for it.

Also, with C++11, you can make the parameters and call in a single function, dynamic:
https://github.com/daid/SeriousProton2/blob/master/include/sp2/script/callback.h#L20

I'm not sure how good the SeriousProton code adapts to this method. (I haven't developed on that engine for quite a while, and put all my learnings from it in SeriousProton2)

**Comment by amir-arad** [comment]
fixes #462

**Comment by czenker** [comment]
> I think you also patched SeriousProton, but didn't submit a patch for it.

The pull request for Serious Proton is here: https://github.com/daid/SeriousProton/pull/23
 
> Also, with C++11, you can make the parameters and call in a single function, dynamic:
> https://github.com/daid/SeriousProton2/blob/master/include/sp2/script/callback.h#L20

That sounds like the better approach because then there is no more state in the ScriptSimpleCallback. Not sure if I get frustrated before I figure out how to make it work, but I will give that approach a try.

**Comment by daid** [comment]
If you don't get the vararg template to work, don't worry, I know it's a bit of black magic. I will accept the patch with out.

**Comment by czenker** [comment]
I have updated both pull requests.

**Comment by daid** [comment]
Great work!

**Pull request merged**
