### PR TITLE
update setting translation scenario_55_defenderHunter.lua

### PR DESCRIPTION
**Pull request by muerteFR**
@Xansta Do I also have to add the line :
difficulty = 1 --default (normal) like in Allies https://github.com/daid/EmptyEpsilon/pull/1624#issuecomment-989039970
although I have no errors on DefenderHunter?

### CODE REVIEW

**Comment by Xansta** [comment]
Probably not

**Comment by daid** [comment]
@Xansta would it be possible to split these settings up into multiple settings now, instead of a single big one?

**Comment by Xansta** [comment]
Absolutely. This is a prime use case. However, I usually adopt changes after a release.

**Comment by daid** [comment]
Prerelease not good enough for ya? :(

**Comment by Xansta** [comment]
I tested a couple of things in the pre-release version, it just has not been my habit to apply scenario script changes to pre-release versions, this official one or "manual" ones. On my Linux box where I do testing, installing a pre-release version supplants the regular version, so I have to install back and forth to switch back and forth. There's probably some way to make them coexist, but I don't have that knowledge. 

To be clear, I think a pre-release is an excellent idea, I just have not been able to take full advantage of it. @muerteFR has been working on translations. He's found a couple of bugs along the way. Where I could, I gave him fixes to incorporate. Should he wish to modify the scenario to use the new variations paradigm, that would be great.

Leaving it as is also tests whether the new variations paradigm is backwards compatible with the current variations paradigm (if backwards compatibility is desired).

Also, I'm lazy and have not revisited a number of the scenarios I am the primary author on to fix and/or enhance.

**Comment by muerteFR** [comment]
As I indicated on Discord https://discord.com/channels/206597597455056898/468130409129967631/922526242597662770 , currently the translations of the settings (Time, Enemies, Playership) don't work.

**Comment by Xansta** [comment]
I tried to make changes to use the `getScenarioSettings()` function, but it didn't work, @daid

**Pull request merged**
