### PR TITLE
Expose mine/missile ownership to scripting and GM info

### PR DESCRIPTION
**Pull request by oznogon**
- Add `getOwner()` to MissileWeapon and Mine objects
- Report MissileWeapon and Mine details (including ownership, homing target, missile lifetime, and faction) via `getGMInfo()`

### CODE REVIEW

**Comment by oznogon** [comment]
Is there a reason for not replicating a missile's owner? If not, I'd just as soon have it replicated and remove the warning. As it stands there's not much value to the function beyond invoking the API since client-side scripts won't have that value.

**Comment by oznogon** [comment]
Example scripting function to report ownership and target info. h/t @Xansta 

```
function listObjects(p, range)
    local missile_list = p:getObjectsInRange(range)
    print("type_name", "heading", "vx", "vy", "md", "owner_callsign", "target_callsign")

    for _, obj in ipairs(missile_list) do
        if obj ~= p then
            local type_name = obj.typeName
            local heading = -1
            if obj:getHeading() ~= nil then
                heading = obj:getHeading()
            end
            local vx = 0
            local vy = 0
            if obj:getVelocity() ~= nil then
                vx, vy = obj:getVelocity()
            end
            local md = distance(p,obj)
            local owner_callsign = "NO OWNER"
            if type_name == "HomingMissile"
                or type_name == "EMPMissile"
                or type_name == "HVLI"
                or type_name == "Nuke"
                or type_name == "Mine"
                then
                if obj:getOwner() ~= nil then
                    owner_callsign = obj:getOwner():getCallSign()
                end
            end
            local target_callsign = "NO TARGET"
            if type_name == "HomingMissile"
                or type_name == "EMPMissile"
                or type_name == "Nuke"
                then
                if obj:getTarget() ~= nil then
                    target_callsign = obj:getTarget():getCallSign()
                end
            end
            print(type_name, heading, vx, vy, md, owner_callsign, target_callsign)
        end
    end
end
```

can result in:

```
type_name	heading	vx	vy	md	owner_callsign	target_callsign
HomingMissile	69.803405761719	187.70269775391	-69.048492431641	1936.0438876447	SS1049	NC102
HomingMissile	253.94567871094	-192.19998168945	55.309722900391	1109.3611355236	BR1056	NC102
```

**Comment by oznogon** [comment]
GM info for a homing missile with target and owner:

Screen Shot 2021-01-26 at 11 46 16 PM

For a mine with owner:

Screen Shot 2021-01-26 at 11 47 46 PM

**Comment by daid** [comment]
The client has no real reason to know the owner. Calling the API client side is sort of chaos anyhow, as a whole bunch of things might and might not be available...

**Comment by Xansta** [comment]
The script does not need the owner if using something like onMissileLaunch(), but until that's available, when the script is looking for a missile that was just launched by going through the list of nearby objects, I don't want to accidentally try to manipulate a different object (or missile from another entity) that just happens to be nearby. This assumes I can get the ID of the player ship so I can match the owner ID provided when querying the missile

**Comment by daid** [comment]
Oh, you missed my point, my point isn't exposing the owner to scripting, that's good, makes perfect sense. My point was the extra `registerMemberReplication`, so the clients know the owners...

**Comment by Xansta** [comment]
Ah, that was me mixing the meanings of "client" and "script" in my head :-)

**Comment by oznogon** [comment]
@daid updated to remove owner_id replication

**Pull request merged**
