### PR TITLE
Script Translations (#1)

### PR DESCRIPTION
**Pull request by lacombet**
This pull request should be link to this issue (I could'nt do it properly for some reason) : 

https://github.com/daid/EmptyEpsilon/issues/767

* Dynamic loading of the scripts on the right language regarding the value of "lang" in options.ini

* comms translation
* factionInfo translation
* science_db translation
* ships translation
* scenario_00_basic translated for references

Warning : Scenarios have been moved from scripts/ to scripts/en_US.
Remaining scenarios should be deleted from scripts/ so they does not appear in the game.

All common data (ships, stations, factions, ...) has been translated. So from now on, scenarios writer must use variable names instead of hard coded string values to refer to those items. Those variables can be found in en_US/ships.lua, en_US/factions.lua ...

When creating a new scenario, please copy/paste it in other languages directories (as-is) so it is found by the game in whatever language it is running.

### CODE REVIEW

**Comment by daid** [comment]
> So from now on, scenarios writer must use variable names instead of hard coded string values to refer to those items.

I do not like that one bit.
A system like gettext would be a lot better. For both the game code and the scripts.
https://en.m.wikipedia.org/wiki/Gettext

**Comment by lacombet** [comment]
Ok I’ll try and implement this.

**Comment by daid** [comment]
I am giving it a shot. Wait a day or so for me to test and document it

**Comment by amir-arad** [comment]
My 2 cents: 
I've recently edited several internal terms in the C++ code (rail-guns instead of beams, that sort of thing) for someone in need. It would be nice to be able to point them in a direction of a language file instead of them needing a developer and custom build.

**Pull request closed without merging**
