### PR TITLE
Use getScenarioSettings in Defender Hunter

### PR DESCRIPTION
**Pull request by Xansta**
Per request in #1639 I have updated the scenario to use the new `getScenarioSettings()` function. I also separated difficulty into enemy ship strength and Murphy's law since `getScenarioSettings()` makes that possible and easy. I also added some additional enemy strength options: "Extreme" and "Quixotic" for the players for whom "Hard" is just not hard enough. I also added support for up to the maximum number of player ships playing simultaneously (currently 32)

### CODE REVIEW

**Comment by muerteFR** [comment]
@Xansta , I have the impression that you made the changes without taking into account the update of the translation contexts that I did. If this PR is pushed, I would have done the work for nothing.

**Comment by Xansta** [comment]
I tried

**Comment by daid** [comment]
I also spotted a bug where you called _() with 3 strings instead of 2 in this change set.

**Comment by muerteFR** [comment]
Where?

**Comment by daid** [comment]
No, bug in this pullrequest

**Comment by muerteFR** [comment]
Ok

**Pull request closed without merging**
