### PR TITLE
Celestial body textures

### PR DESCRIPTION
**Pull request by Xansta**
### A few alternatives for planets and moons and such
(edited based on feedback below)
- `planet-3.png` is a condensed version of Venus. Data obtained from [astrogeology.usgs.gov](https://astrogeology.usgs.gov/search/details/Venus/Magellan/Colorized/Venus_Magellan_C3-MDIR_Colorized_Global_Mosaic_4641m/cub) which is identified as being in the public domain
- `planet-4.png` and `gas-3.png` were taken from [textures for planets](https://www.texturesforplanets.com/), the origin of some of the other planetary textures
- `gas-2.png` (Saturn), `moon-2.png` (Daedalus) and `moon-3.png` (Titan) came from the [Celestia](https://github.com/CelestiaProject) project
- @oznogon generated `planet-5.png`
- The clouds came from [wikimedia commons](https://commons.wikimedia.org/wiki/File:Fair_Weather_Cloud_Map.jpg) and were scaled and transformed to purpose

I placed the files in the resources/planets directory and used this lua script to test them out:
```lua
-- Name: Magrathea
-- Description: Planetary catalog
-- Type: Planetary Catalog
function init()
	local angle = 90
	PlayerSpaceship():setTemplate("Crucible"):setHeading(angle):commandTargetRotation((angle + 270) % 360)
	texture_list = {
		"atmosphere",
		"clouds-1",
		"clouds-2",	--new
		"clouds-3",	--new
		"gas-1",
		"gas-2",	--new
		"gas-3",	--new
		"moon-1",
		"moon-2",	--new
		"moon-3",	--new
		"planet-1",
		"planet-2",
		"planet-3",	--new
		"planet-4",	--new
		"planet-5",	--new
		"star-1",
	}
	large_surface = "gas-1"
	large_atmosphere = "No"
	large_clouds = "none"
	cr = 0	--color red value
	cg = 0	--color green value
	cb = 0	--color blue value
	large_planet = Planet():setPosition(10000,0):setPlanetRadius(4000):setDistanceFromMovementPlane(-2000)
	large_planet:setPlanetSurfaceTexture("planets/" .. large_surface .. ".png"):setAxialRotationTime(300)
	setGMFunctions()
end
function setGMFunctions()
	clearGMFunctions()
	addGMFunction(string.format("+Surface %s",large_surface),setLargeSurface)
	addGMFunction(string.format("Atmosphere %s",large_atmosphere),function()
		if large_atmosphere == "No" then
			large_atmosphere = "Yes"
			large_planet:setPlanetAtmosphereTexture("planets/atmosphere.png")
		else
			large_atmosphere = "No"
			large_planet:setPlanetAtmosphereTexture("")
		end
		setGMFunctions()
	end)
	addGMFunction(string.format("+Color %.2f %.2f %.2f",cr,cg,cb),setColor)
	addGMFunction(string.format("+Clouds %s",large_clouds),setLargeClouds)
end
function setLargeSurface()
	clearGMFunctions()
	for _, texture in ipairs(texture_list) do
		local button_label = texture
		if button_label == large_surface then
			button_label = button_label .. "*"
		end
		addGMFunction(button_label,function()
			large_surface = texture
			large_planet:setPlanetSurfaceTexture("planets/" .. large_surface .. ".png")
			setGMFunctions()
		end)
	end
end
function setColor()
	clearGMFunctions()
	addGMFunction("-Main",setGMFunctions)
	if cr < 1 then
		addGMFunction(string.format("Red %.2f +",cr),function()
			cr = cr + .01
			large_planet:setPlanetAtmosphereColor(cr,cg,cb)
			setColor()
		end)
	end
	if cr > 0 then
		addGMFunction(string.format("Red %.2f -",cr),function()
			cr = cr - .01
			large_planet:setPlanetAtmosphereColor(cr,cg,cb)
			setColor()
		end)
	end
	if cg < 1 then
		addGMFunction(string.format("Green %.2f +",cg),function()
			cg = cg + .01
			large_planet:setPlanetAtmosphereColor(cr,cg,cb)
			setColor()
		end)
	end
	if cg > 0 then
		addGMFunction(string.format("Green %.2f -",cg),function()
			cg = cg - .01
			large_planet:setPlanetAtmosphereColor(cr,cg,cb)
			setColor()
		end)
	end
	if cb < 1 then
		addGMFunction(string.format("Blue %.2f +",cb),function()
			cb = cb + .01
			large_planet:setPlanetAtmosphereColor(cr,cg,cb)
			setColor()
		end)
	end
	if cb > 0 then
		addGMFunction(string.format("Blue %.2f -",cb),function()
			cb = cb - .01
			large_planet:setPlanetAtmosphereColor(cr,cg,cb)
			setColor()
		end)
	end
end
function setLargeClouds()
	clearGMFunctions()
	addGMFunction("None",function()
		large_clouds = "none"
		large_planet:setPlanetCloudTexture("")
		setGMFunctions()
	end)
	for _, texture in ipairs(texture_list) do
		if string.find(texture,"cloud") then
			local button_label = texture
			if button_label == large_clouds then
				button_label = button_label .. "*"
			end
			addGMFunction(button_label,function()
				large_clouds = texture
				large_planet:setPlanetCloudTexture("planets/" .. large_clouds .. ".png")
				setGMFunctions()
			end)
		end
	end
end
```

### CODE REVIEW

**Comment by oznogon** [comment]
You might want to include the licensing info for gas-2.png, gas-3.png and moon-2.png, even if it's allowed. It doesn't explicitly require attribution, but the terms aren't very clear.

Also, I have some generated textures that can be PD/CC0 licensed. Will attach.

**Comment by Xansta** [comment]
From the website where I got gas-2.png (neptune), gas-3.png (saturn) and moon-2.png (pluto):
Quote
Copyright Information
All textures and images on this site are Copyright (c) by James Hastings-Trew. The maps are free to download and use as source material or resource in artwork or rendering (CGI or real time) in any kind of project - personal, commercial, broadcast, or display. You are not free to redistribute the maps "as is" in any medium - online, CD, for sale, etc. where the primary intent is to distribute the maps themselves and not the result of using the maps, without my permission. That is to say, the results of using the maps are free to use and distribute, but the maps as direct source material for those results may not be, unless you have my permission. The maps may not be included as they exist on this site in any kind of commercial, shareware, or freeware product without my permission. The maps may not be repackaged with 3D models and sold in any form. The maps may not be given away in whole or in part on another website or in a freeware or commercial product without my permission.

Here are some examples of usage that I hope will clear the situation up:

Example 1 - The Simulator or Game
You are a software author who has created a Solar System simulator and you want to use my planet texture maps in your program. Since the primary intent of your use is to create real time renderings utilizing the planet texture maps as a resource in your software product, this is an acceptable use under my copyright terms.
Unquote

**Comment by oznogon** [comment]
No, I read it. But since these will be included unobfuscated in the distribution of something with a different license, we should note that this artwork is used under different terms than the rest.

**Comment by Xansta** [comment]
It's unclear to me exactly where to put that kind of information, so I put it here with the idea that either someone will put it where it belongs or direct me to the location where it should live. Alternatively, if it turns out to be a show stopper, those files can be removed from the pull request.

**Comment by oznogon** [comment]
In other similar instances within the project, there's a `LICENSE` file in the same directory as the files:

resources/packs/License.txt
resources/gui/fonts/LICENSE

**Comment by aBlueShadow** [comment]
About the 3 textures in question, I think more FOSS-compatible licenses are preferable. Especially when there are already similar textures in another GPL2 project. Like here https://github.com/CelestiaProject/Celestia/tree/master/textures (no good pluto map though, but the pluto texture in your PR is fictional anyways and by now there are pretty detailed maps for pluto, thanks to new horizons).

**Comment by oznogon** [comment]
Looks like the existing planet textures were generated by Textures for Planets: https://www.texturesforplanets.com/

I've attached several more planet images generated by it, all at the same 2048x1024 resolution as the existing textures.

These have no licensing requirements imposed by the software, no attribution is required, and I'm releasing all of them into the public domain.

gas-4
gas-5
gas-6
gas-7
gas-8
ice-1
ice-2
moon-3
moon-4
planet-5
planet-6

**Comment by Xansta** [comment]
Those are great! I liked the Pluto that I put out there, but I can live without it. I mainly wanted more than 1 moon and 2 planets to choose from in the stock game.

**Comment by oznogon** [comment]
There are some CC-BY 4.0 solar system textures (only attribution required) at https://www.solarsystemscope.com/textures/

**Comment by aBlueShadow** [comment]
@Xansta 
> I liked the Pluto that I put out there

As that was basically a modified ganymede map, you could use the ganymede texture from the link I posted above

@oznogon great link! Especially for scenarios that take place in our solar system (and other than the celestia link, there is a ready-to use earth texture)

**Comment by Xansta** [comment]
I replaced textures I deleted earlier with textures from the celestial project and textures for planets as mentioned by @oznogon and @aBlueShadow 

Celestial project: gas-2 (Saturn), moon-2 (Enceladus), moon-3 (Titan)
Textures for planets: gas-3, planet-4

**Comment by oznogon** [comment]
I remembered that I had Fractal Terrains 3, so I spun off some terrestrial worlds as well:

fractal-1-barren
fractal-1-lush
oasis-1

**Pull request merged**
