### PR TITLE
Scenario_49_allies.lua add 752 _() and description translation updated

### PR DESCRIPTION
**Pull request by muerteFR**
69 Back
4 ZoneLabelDescription-faction
1 scienceDescription-planet
77 scienceDescription-station
39 ammo-comms
13 gossip-comms
17 station-comms
20 stationAssist-comms
50 stationStory-comms
57 stationGeneralInfo-comms
89 trade-comms
20 needRep-comms
2 ship-comms
23 shipEnemy-comms
18 shipAssist-comms
2 explainGoods-comms
21 explainGoodsComponent-comms
8 explainGoodsMineral-comms
5 explainGoodsTrade-comms
2 explainGoodsVapor-comms
4 orders-comms
23 msgMainscreen
1 msgEngineer
1 msgEngineer+
3 buttonGM
7 path-comms
3 coolant-tabEngineer
1 coolant-buttonEngineer
1 coolant-buttonEngineer+
32 inventory-shipLog
1 inventory-buttonRelay
1 inventory-buttonOperations
12 characterInfo-comms

11 doomsday-comms
2 doomsdayOrders-comms
4 doomsday-shipLog
1 doomsdayGoal-shipLog
3 doomsday-tabEngineer&Engineer+
1 doomsday-msgMainscreen

89 doctor-comms
2 doctorOrders-comms
4 doctor-shipLog
1 doctorGoal-shipLog
1 doctor-tabScience&Operations
1 doctor-msgMainscreen

1 BespinOrders-comms
2 Bespin-shipLog
1 BespinGoal-shipLog
1 Bespin-msgMainscreen

### CODE REVIEW

**Comment by muerteFR** [comment]
If I change Variation to Setting (see 2 lasts commits), it generates the following error. see photo.
Am I undoing this change to already push the _ () tags? Or is it easy to fix?

allies probleme

**Comment by Xansta** [comment]
The function `getScenarioSetting` is not part of version 2021623, but part of the new release. In version 2021623, the proper function is `getScenarioVariation`

They are similar, but different enough that just changing the name is insufficient. It is unclear to me whether `getScenarioVariation` will still be supported in the new version. If not, this script among several will be broken with the new release unless someone is going through the scenarios to convert from `getScenarioVariation` to `getScenarioSetting`

Perhaps @daid can speak to this

**Comment by muerteFR** [comment]
In fact Xansta, that's exactly what I'm doing, converting getScenarioVariation to getScenarioSetting. And I test them with a compiled version of 13112021. With this version, other already converted scenarios work well (Waves, Basic). That's why I don't know why with Allies there is this error.

**Comment by Xansta** [comment]
Looks like you only did a partial conversion. You took the previous version's scenario variations and lumped them into a setting called "Enemies" then you did not use "Enemies" as your lookup criteria. I suggest you replace
`getScenarioSetting()` with `getScenarioSetting("Enemies")`

**Comment by muerteFR** [comment]
Yes thank to you Xansta I just saw my forgetfulness. I will rectify that.

**Comment by muerteFR** [comment]
AlliesSettings


It works except for "One"
Look at the Basic scenario for example as a model. Does Allies need more modifications? to separate "One" from "3missions"? And for "Timed" line 147. I'm not sure it's enough for this scenario to just change the names like I did for Waves? In this case it is better that I cancel my last 2 commits and that I already push the additions of tags _ ().

**Comment by Xansta** [comment]
Copy this line:
`difficulty = 1		--default (normal)`
...and insert it between these two lines:
```
function setSettings()
	if string.find(getScenarioSetting(),"Easy") then
```
...so that difficulty is always set to the default value initially

**Comment by muerteFR** [comment]
the error has disappeared

**Pull request merged**
