### PR TITLE
Added scenario script, Deliver Ambassador Gremus

### PR DESCRIPTION
**Pull request by Xansta**
Pull request includes the scenario script .lua file and audio files triggered by the script at particular points in the mission. Script has been tested with local players. Server was a Linux installation and the clients were Windows release installations.

### CODE REVIEW

**Comment by Xansta** [comment]
Nice catch. I'll fix that. I wondered why I did not see too many transports, but then I was focused on the main plot line.

**Comment by Xansta** [comment]
Corrected variable name mismatch.

**Comment by NinjaSpectre** [comment]
I also have some suggestions for the Treasure Hunt portion.  https://github.com/NinjaSpectre/EmptyEpsilon/commit/9ac3c9f5e8dd6b8dd93f556a5bb303e55ba8f538
I propose finding them all, please disregard if it does not fit into the story.

**Comment by Xansta** [comment]
Hi,

The "treasure hunt" is my initial attempt at artifact interaction. One was supposed to explode, one was going to have the possibility of being picked up. The mission completion criteria just has one being good enough to complete the mission. With more testing, I was going to make this interaction more complicated like may getting clues to the next artifact from information on the first one investigated. I don't mind making finding all three a requirement.

The story is certainly not fixed. 
--------------------------------------------
On Thu, 1/11/18, NinjaSpectre <notifications@github.com> wrote:

 Subject: Re: [daid/EmptyEpsilon] Added scenario script, Deliver Ambassador Gremus (#515)
 To: "daid/EmptyEpsilon" <EmptyEpsilon@noreply.github.com>
 Cc: "Xansta" <priddys@yahoo.com>, "State change" <state_change@noreply.github.com>
 Date: Thursday, January 11, 2018, 2:56 PM
 
 I also have some suggestions for
 the Treasure Hunt portion.  NinjaSpectre/EmptyEpsilon@9ac3c9f
 
 I propose finding them all, please disregard if it does not
 fit into the story.
 
 —
 You are receiving this because you modified the open/close
 state.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by daid** [comment]
I haven't tried this mission yet, is it good enough to merge into the main branch yet? The look looks fine at a first glance.

**Comment by Xansta** [comment]
I feel it's complete enough and bullet proof enough to merge. I recommend inclusion with the reservation that it can be modified in the future if feedback comes in with problems or suggested improvements.

I've tested it myself and tried it with my local group of players. 


--------------------------------------------
On Thu, 2/8/18, daid <notifications@github.com> wrote:

 Subject: Re: [daid/EmptyEpsilon] Added scenario script, Deliver Ambassador Gremus (#515)
 To: "daid/EmptyEpsilon" <EmptyEpsilon@noreply.github.com>
 Cc: "Xansta" <priddys@yahoo.com>, "State change" <state_change@noreply.github.com>
 Date: Thursday, February 8, 2018, 1:10 PM
 
 I haven't tried this mission
 yet, is it good enough to merge into the main branch yet?
 The look looks fine at a first glance.
 
 —
 You are receiving this because you modified the open/close
 state.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by daid** [comment]
Naturally you can always send in patches/improvements/fixes :-)

**Pull request merged**
