### PR TITLE
shipTemplatess: fix typos

### PR DESCRIPTION
**Pull request by capt-t**
2 questions:

- in OLD: _adoptation_ -> adoption or adaptation?

  > Due to it's versatility, this ship has found wide _adoptation_ in most factions. Most factions have extensively retrofitted these ships to suit their combat doctrines. Because it's an older model, most factions have been selling stripped versions. This practice has led to this ship becomming an all time favourite with smugglers and other civillian parties. However, they have used it's adaptable nature to re-fit them with (illegal) weaponry.

- maybe BE -> AE in: _savoury_, _favourite_

### CODE REVIEW

**Comment by daid** [comment]
Guess with [WIP] I can mark this as a draft? :)

**Comment by capt-t** [comment]
Actually, this could already be merged. But if we answer at least the first question, it will become a "completer" commit.

**Comment by daid** [comment]
Pretty sure I intended adaptation (sorry, missed the question)

**Comment by capt-t** [comment]
Okay, adaptation.
(adoption of course in the sense of "the decision to start using something such as an idea, a plan or a name")

Done.

Someone might want to have a look at the translation files.

**Pull request merged**
