### PR TITLE
Use PNG alpha for radar drop shadow overlay

### PR DESCRIPTION
**Pull request by oznogon**
Replace the opaque background image with a transparent/alpha-shaded overlay. This allows the background color configured in `colors.ini` to appear.

This also adds custom shadows for the Science/Ops screens, which has a larger radar shifted left, and the single-pilot overlay, which has a smaller radar.

### CODE REVIEW

**Comment by InterestingJohn** [comment]
Any way I can see a screenshot of this? (mostly curious)

**Comment by Fouindor** [comment]
http://i.imgur.com/2Qx2ubq.png
http://i.imgur.com/84UEBYh.png (with a #FF0000 backdrop)
http://i.imgur.com/ZokfjiL.png (Science)

Quite nice, the only remark I have is that in the database, the gradient still shows.

**Comment by InterestingJohn** [comment]
Outstanding!

**Comment by oznogon** [comment]
Thanks @Fouindor. #315 should fix this for the database.

**Pull request merged**
