### PR TITLE
Improve code of scenarios 0 to 10 (part 1)

### PR DESCRIPTION
**Pull request by capt-t**
This pull requests addresses scenarios 0 to 10 and prepares further code improvements and possible refinements or additions the scenarios.

The comments are extended and their formatting is standardized.

EE ist not affected.

Make scenarios (0 to 10) and other lua files in the `scripts` folder compilable by [LDoc](https://stevedonovan.github.io/ldoc/). This will help future improvements in the scripts.

With LDoc, you can now run:
    
- `ldoc scenario_00_basic.lua` to generate an HTML page in the `doc` directory.
- `ldoc -m scenario_00_basic` to get an overview of functions etc.
- `ldoc -m scenario_00_basic.addWave` to get details for this function.

In addition to this, some IDEs may give peeks and better code completion.

The changes do not modify the scenarios themselves.

The changes in the comments:

- Start the files with an LDoc comment `---` followed by lines with `--`.
  - In scenario files (where EE expects a certain beginning), the LDoc comment follows after a blank line. (Unfortunately, this hides the description for the documentation, but that is okay.)
- Similarly for the comments of functions.
- Move comments to the proper position (above the function, not in it), tag parameters, add return types, improve comments. (Markdown is possible.)
- Add a few comments and dummy comments for functions to make them indexed.
- Most files are marked as `@script`, not as `@module` (default).
- Add `scripts/.gitignore` to ignore generated doc files.
- Structure by `@section`, see e.g. 08_atlantis.

The generated files are not included.

### CODE REVIEW

**Comment by capt-t** [comment]
Improved version, ordered by scenario, rebased to `master`. (Check the commits in sequence, not by date as GitHub shows them.)
Should be ready for merge.

**Comment by capt-t** [comment]
Currently under revision. Will be ready for merge soon.

**Comment by capt-t** [comment]
Simpler version. Ready for merge.

**Comment by daid** [comment]
> (Unfortunately, this hides the description, but okay.)

Hides the description from what?

**Comment by capt-t** [comment]
Oh, that is not a problem for EE. Only the scenario description does not go to generated documentation.

Documentation expects the file to start with a `--- ...` line, but EE does not like that.

Adding a second comment like
```lua
--- Scenario.
--
-- (Here could be a description, but let us not duplicate it.
--
-- @scenario a_unique_key_eg_the_filename

```

makes the file parsable by tools like `ldoc`. It does not affect EE at all.

**Pull request merged**
