### PR TITLE
Adding functionality to HTTP api and binding UI to ship state

### PR DESCRIPTION
**Pull request by Tuhis**
This pull request adds some new functions to HTTP api to be able the ship through it. At this point I've gone through weapons and engineering stations.

Added functions:
- commandNextTarget
- commandPreviousTarget
- commandFireTubeAtCurrentTarget
- commandCalibrateShields
- commandSetShieldFrequencySelection
- commandSetNextShieldFrequencySelection
- commandSetPreviousShieldFrequencySelection
- commandConfirmSelfDestruct
- commandSetAimLock
- commandSetAimAngle
- commandSelectWeapon
- commandSelectSystem

Also, I've bound UI state to ship's state where it wasn't yet. Related issue: https://github.com/daid/EmptyEpsilon/issues/605

CMakeLists.txt and FindSFML.cmake modifications are something that I had to do to get build working for me... I'm not sure if they should be merged or not.

### CODE REVIEW

**Comment by daid** [comment]
I have a few issues with this pull request:

- Unrelated build system file changes
- It moves a few things server side, that should be client side in my opinion. Like system selection for the engineering station. Else if multiple people look at engineering, the selected system can change while you are adjusting things.
- Not sure why you put spaces around the ```->``` operator, I've never seen that before...

So while there are some good fixes in there, as a whole it's a bit too much.

**Comment by Tuhis** [comment]
Spaces around the ”->” operator are mistake, shouldn’t be there. Also I can get rid of build system changes.

Selected system and other similar things are moved to server side to be able to control the ship through the api. Otherwise the requests must be sent to correct EE client which is a bit too tough requirement in my opinion. Is there some situation when multiple people would be looking at a single station (e.g. engineering)?

**Comment by aBlueShadow** [comment]
> Selected system and other similar things are moved to server side to be able to control the ship through the api.
You don't need to remote control the station to control the ship, you can just do it directly by things like commandSetSystemPowerRequest. As system selection is a client thing, you can just implement it in your webapp or whatever you are using for the http api. Or you have just a bund of sliders, like in the power control-screen to allocate power and coolant directly.
I would put it that way: By using the http API you are not controlling a station, you are (re)making one.

**Comment by daid** [comment]
> Is there some situation when multiple people would be looking at a single station (e.g. engineering)?

Yes, when there are for example 3 people controlling a ship. Multiple people might take the engineering station.

I'm always open for more APIs, and there are a few things in here that I like. But I don't like moving things server side that should be client side. This can also cause odd UI jittering with the manual targeting for example.

And, for example gui2_rotationdial.cpp suddenly knows about the player spaceship now, and that's not right for a "generic" control. Even tough it is used in only 1 spot.

**Pull request closed without merging**
