### PR TITLE
better doc for onNewPlayerShip

### PR DESCRIPTION
**Pull request by HagenRo**
once in a while a wild doc addition appears

### CODE REVIEW

**Comment by HagenRo** [comment]
and as I'm confused by the callback interaction I'll ask it here.

why is this working:
`onNewPlayerShip(
    function(ship)
        initializePlayership(ship)
    end
)`

while this is not working:
`onNewPlayerShip(test)
test = function(ship)
    initializePlayership(ship)
end`

note there is no error occuring.

In my understanding there should be no difference between the anonymous function and the fuction reference.
What am I missing?

**Comment by daid** [comment]
```
onNewPlayerShip(test)
test = function(ship)
    initializePlayership(ship)
end
```
Doesn't work because you use `test` before you assign it. So it's `nil` at that point, which is handled as "no callback"

```
function test(ship)
    initializePlayership(ship)
end
onNewPlayerShip(test)
```
Should work fine.

**Comment by HagenRo** [comment]
I hate languages that don't load all functions befor execution :(

**Comment by daid** [comment]
It's why the scenarios have an `init` function. You can define all your functions nicely in whatever order you want, and in the `init()` you do the `onNewPlayerShip(...)`

**Pull request merged**
