### PR TITLE
Added custom radar images

### PR DESCRIPTION
**Pull request by Fouindor**
Added the possibility to use custom radar images for ships and stations. These images can be set using the new setRadarTrace(string filename) function.

If a ship is not identified, it will display using the default "RadarArrow.png" image. If identified by the science station and that a custom image has been set, it will display using the custom image.

Differs from my previous pull request in that I have added that if a radar image is not set, it will default to the standard image for the object.

### CODE REVIEW

**Comment by daid** [comment]
Looks good. See a few minor things that could be improved in your coding skills, but overall it's a good patch.

"bools" for example should be set to "true" or "false", instead of 1 and 0. Does the same, but makes it more readable.

**Comment by daid** [comment]
Did some extra work on your patch. Also added functions to overrule the custom icon on a ship-by-ship basis during scenarios.

**Comment by Fouindor** [comment]
Thank you ! :)
I'm still learning a lot of things about "real" coding ^^

Indeed, having a function that sets an icon on-the-fly is good, especially for designating a "special" ship without setting a new template.

**Comment by daid** [comment]
Also allows you to "mark" a ship on the radar, by using the same icon with a circle around it.

Learning is good, that's why I tell you what I did and why :-)

**Pull request merged**
