### PR TITLE
Website Updates Round 2

### PR DESCRIPTION
**Pull request by InterestingJohn**
Ok, second round of big updates to the website design

added styles for “tabs inside tabs”
added icons for stations
added new jQuery for screenshot viewing
updated styles for vertical tabs

Next up is cleaning up the download page, then working on making the whole thing more responsive.

### CODE REVIEW

**Comment by InterestingJohn** [comment]
Ok, I think I fixed my screwup :P let me know if something doesn't look right, I'm still fairly new to GitHub.

**Comment by daid** [comment]
Not sure how you managed it, but it wants to merge into the "master" branch, while it should merge into the "gh-pages" branch.

I can see if I can merge it properly tomorrow.

**Comment by InterestingJohn** [comment]
I thought I was able to remove that particular commit (I'm honestly not sure how I managed that either).

**Comment by InterestingJohn** [comment]
Some more big updates, biggest of all is adding responsive design to the mix.

**Comment by daid** [comment]
Merged it by hand (as github still wants to merge it into the source code branch). Looking good :-)

**Pull request closed without merging**
