### PR TITLE
Change ship signatures based on system states

### PR DESCRIPTION
**Pull request by oznogon**
Ship signatures can change based on their heat, power level, and
usage.

- Systems that generate heat increase the biological band; coolant
  offsets this effect even if the system maintains heat.
- Systems that use energy increase the electrical band.
- Ships that are jumping or warping spike the gravity band.

This allows Science to predict when a ship is going to warp/jump,
and in stealth missions can give away the positions of ships that
run hot.

CPU ships do not manage heat/energy but still exhibit jump/warp
spikes.

Example of a jump spike before and after:

jumping
jumping2

Progress toward #14

### CODE REVIEW

**Comment by tdelc** [comment]
I like this PR, bit do you test it with old computers ? I have huge lags
with my old PCs for the science station and I am afraid it could be worse
with your feature.

**Comment by daid** [comment]
Dont think it will effect performance at all. But it does break setting custom signatures from scripting i think.

**Comment by oznogon** [comment]
Ah, good point @daid — I'll revise.

**Comment by daid** [comment]
I also think this causes unneeded network traffic. As the signature is calculated on clients now as well as send to clients.

**Comment by oznogon** [comment]
If I understand correctly, it should be straightforward to move the loop into an `if (game_server)` condition to fix the network redundancy?

**Comment by oznogon** [comment]
Updated the branch to move the logic to the RawScannerDataRadarOverlay component and changed the behavior on further testing.

- Coolant use can no longer result in negative bio band values.
- Jump drive grav spikes start small and grow larger closer to the jump.
- Jump drive recharge state causes an electrical spike that drops
  the closer the system gets to being fully recharged, and scales to the
  system's power level.
- A ship's electrical signature can be reduced by underpowering its systems.

The baseline radar signature is also slightly lower now to add some contrast between an idle and active ship.

**Comment by daid** [comment]
I was thinking this logic could also be moved to the "getRadarSignatureInfo" function, which could have been made virtual then and overloaded in the spaceship. However, that would mean the set and get functions would return different data, which is odd. So I've accepted this solution.

**Pull request merged**
