### PR TITLE
gameGlobalInfo: getSectorName

### PR DESCRIPTION
**Pull request by capt-t**
Make `getSectorName` for coordinates available in Lua.

### CODE REVIEW

**Comment by capt-t** [comment]
Suggestions to fix this?

**Comment by capt-t** [comment]
Okay.

Could we replace
```cpp
string getSectorName(sf::Vector2f position)
{
    int sector_x = floorf(position.x / sector_size) + 5;
```
with the following?
```cpp
string getSectorName(lua_State* L)
{
    float x = luaL_checknumber(L, 1);
    // ...
    int sector_x = floorf(x / sector_size) + 5;
}
```
But this changes the signature.

Or is it better to introduce this function?
```cpp
string getSectorNameXY(lua_State* L)
{
    return getSectorName(x, y);
}
```

**Comment by NinjaSpectre** [comment]
Close... it can be done by adding the following.  I named the additional function the same.
```c++
int getSectorName(lua_State* L)
{
    float x = luaL_checknumber(L, 1);
    float y = luaL_checknumber(L, 2);
    sf::Vector2f position(x, y);
    lua_pushstring(L, getSectorName(position).c_str());
    return 1;
}
```

**Comment by capt-t** [comment]
I see the interaction between C++ and Lua.

Thank you!

**Pull request merged**
