### PR TITLE
Compile script docs

### PR DESCRIPTION
**Pull request by capt-t**
Improve (docstring and) output of `compile_script_docs.py`.

In particular, list possible string values of several parameter types of the Lua functions.

### CODE REVIEW

**Comment by Kilted-Klingon** [comment]
I've not looked at it, but this certainly does seem like it would be useful.  Thanks @capt-t !

**Comment by daid** [comment]
I think it would be better to document the types at the conversion function, for example at this function:
https://github.com/daid/EmptyEpsilon/blob/master/src/playerInfo.cpp#L263
And then extract that data as well. This will also allow the document generator to link to these types instead of them being hardcoded.

**Comment by capt-t** [comment]
I agree that this would be the best solution. But so far this was not possible: To which object or function should the comment lines be added to? The C types are not included in the reference.

At first I had considered to mention the values for `EAlertLevel` at `commandSetAlertLevel`, but I wanted to explain each type only once. The current place is not the perfect solution, but better than the non-documentation before. It was annoying to find the correct capitalization of "RED ALERT" vs. "Normal".

After `compile_script_docs.py` has been extended, the comments are easy to move.

**Comment by capt-t** [comment]
Mentioned the possible improvement in the python file.

Fixed the examples of `ScriptStorage`.

**Pull request merged**
