### PR TITLE
Factions control

### PR DESCRIPTION
**Pull request by amir-arad**
(based on #597)

GM screen controls the diplomatic status of every two factions.

### CODE REVIEW

**Comment by nallath** [comment]
I think it's a shame this never got merged. Is there a chance you could look at fixing the merge conflicts?

**Comment by tdelc** [comment]
Amir, if you dont have time, I will put it in my larp version, based the
last vanilla version. So i could plan to PR it once again.

Le jeu. 27 août 2020 à 20:44, Jaime van Kessel <notifications@github.com> a
écrit :

**Comment by nallath** [comment]
I'm also going to be running a LARP with EE next year, so I'm trying to pick up this project a bit more (since I'd like to be at least more than passingly familliar with this). I could also have a look at fixing this, but generally speaking merge conflicts are easier to fix by the original author.

**Comment by tdelc** [comment]
Yes of course, it is easier for the original author. If I need to put this new feature by myself, I think I will restart from the beginning...

If you are interested by EE for LARP, you can take a look on my fork https://github.com/tdelc/EmptyEpsilon
I try to follow vanilla game advancements and add optional features for a LARP perspective (from now : drones system, multi waypoint color, multi GM support, color by faction and not because friend or ennemy, ...).

**Comment by nallath** [comment]
Ah, cool. I'll have a look at your changes!

**Comment by daid** [comment]
I was reminded about this pull request. Closing at the moment. Few reasons:
- There are a ton of unrelated changes (pull request too big)
- It does not actually work. There is no network replication happening, so clients are unaware of the changes and thus FoF indicators will be wrong.

**Pull request closed without merging**
