### PR TITLE
Revert "i18n for alert levels"

### PR DESCRIPTION
**Pull request by daid**
Reverts daid/EmptyEpsilon#812

### CODE REVIEW

**Comment by aBlueShadow** [comment]
What was the reason for this? I know it might look suspicious (similar to those functions that needed a locale counterpart), that's why I split it from the relay-PR. However IMO it is different in this case, as it only affects the button labels on the relay console, and alertLevelToString is not called from any other place. Or did I miss something?

**Comment by daid** [comment]
It broke a script function on the player ship there is the `getAlertLevel` function which would have returned localized data. Missed that before I merged.

**Comment by aBlueShadow** [comment]
Hm.. I looked into getAlertLevel back then and it looked like it only gets the EAlertLevel to me.
https://github.com/daid/EmptyEpsilon/blob/64523908a7d68132850dd4a5cd5eec7c3caf10b4/src/spaceObjects/playerSpaceship.h#L267

**Comment by daid** [comment]
And that is converted by this function:
https://github.com/daid/EmptyEpsilon/blob/3646a96efb32b974e0e9c4bf5ea73911cb37cfa9/src/spaceObjects/playerSpaceship.hpp#L6

**Comment by aBlueShadow** [comment]
oh I see. learning more every day

**Comment by daid** [comment]
The whole lua script binding uses quite a bit of magic :)

**Pull request merged**
